const KEY='afrocare_v1';
const seed={patients:[{id:'P-1042',name:'Aarav Sharma',age:34,gender:'Male',condition:'Hypertension',status:'Admitted',doctor:'Dr. Meera Rao'},{id:'P-1041',name:'Priya Nair',age:28,gender:'Female',condition:'Migraine',status:'Stable',doctor:'Dr. Kabir Khan'},{id:'P-1040',name:'Rohan Verma',age:51,gender:'Male',condition:'Diabetes',status:'Admitted',doctor:'Dr. Meera Rao'},{id:'P-1039',name:'Ananya Singh',age:22,gender:'Female',condition:'Fever',status:'Discharged',doctor:'Dr. Sana Ali'}],appointments:[{id:'A-221',patient:'Aarav Sharma',doctor:'Dr. Meera Rao',date:'2026-09-08',time:'10:30',type:'Follow-up',status:'Confirmed'},{id:'A-220',patient:'Priya Nair',doctor:'Dr. Kabir Khan',date:'2026-09-08',time:'11:15',type:'Consultation',status:'Confirmed'},{id:'A-219',patient:'Rohan Verma',doctor:'Dr. Meera Rao',date:'2026-09-09',time:'09:45',type:'Review',status:'Pending'}],doctors:[{name:'Dr. Meera Rao',specialty:'Cardiology',room:'C-204',status:'On duty'},{name:'Dr. Kabir Khan',specialty:'Neurology',room:'N-102',status:'On duty'},{name:'Dr. Sana Ali',specialty:'General Medicine',room:'G-110',status:'Off duty'},{name:'Dr. Arjun Patel',specialty:'Orthopedics',room:'O-305',status:'On duty'}],beds:Array.from({length:18},(_,i)=>({no:i+1,status:i<11?'Occupied':i<15?'Clean':'Available',ward:i<6?'General':i<12?'Private':'ICU'})),invoices:[{id:'INV-082',patient:'Aarav Sharma',amount:18400,status:'Paid',date:'2026-09-07'},{id:'INV-081',patient:'Priya Nair',amount:5200,status:'Pending',date:'2026-09-06'},{id:'INV-080',patient:'Rohan Verma',amount:12750,status:'Paid',date:'2026-09-05'}]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; let current='dashboard';
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(db));$('#storageStatus').textContent='Saved';setTimeout(()=>$('#storageStatus').textContent='Ready',900)}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function layout(title,kicker){$('#pageTitle').textContent=title;$('#pageKicker').textContent=kicker;render()}
function render(){if(current==='dashboard')dashboard();if(current==='patients')patients();if(current==='appointments')appointments();if(current==='doctors')doctors();if(current==='wards')wards();if(current==='billing')billing();if(current==='settings')settings()}
function dashboard(){const admitted=db.patients.filter(p=>p.status==='Admitted').length; const pending=db.appointments.filter(a=>a.status==='Pending').length; const revenue=db.invoices.reduce((s,i)=>s+i.amount,0);$('#content').innerHTML=`<section class="hero"><div><span class="subtle" style="color:#a9c0b5">TUESDAY · SEPTEMBER 08, 2026</span><h2>Good morning, Admin.</h2><p>Here's what's happening across your hospital today.</p></div><div class="date-pill">● System operational</div></section><section class="stats"><div class="stat"><div class="stat-top"><span>Total patients</span><i class="stat-icon">♙</i></div><h3>${db.patients.length}</h3><span class="trend">↑ 8.2% this month</span></div><div class="stat"><div class="stat-top"><span>Admitted</span><i class="stat-icon">+</i></div><h3>${admitted}</h3><span class="trend">Active care</span></div><div class="stat"><div class="stat-top"><span>Appointments</span><i class="stat-icon">◷</i></div><h3>${db.appointments.length}</h3><span class="trend">${pending} pending</span></div><div class="stat"><div class="stat-top"><span>Billing</span><i class="stat-icon">₹</i></div><h3>₹${revenue.toLocaleString('en-IN')}</h3><span class="trend">Collected + pending</span></div></section><section class="dashboard-grid"><div class="panel"><div class="panel-head"><div><h3>Recent patients</h3><span class="subtle">Latest records in the system</span></div><button class="btn ghost" onclick="go('patients')">View all</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Condition</th><th>Doctor</th><th>Status</th></tr></thead><tbody>${db.patients.slice(0,5).map(p=>`<tr><td><div class="patient"><span class="mini-avatar">${initials(p.name)}</span><b>${esc(p.name)}</b></div></td><td>${esc(p.condition)}</td><td>${esc(p.doctor)}</td><td><span class="badge ${p.status==='Discharged'?'warn':''}">${p.status}</span></td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><div><h3>Today's activity</h3><span class="subtle">Live local activity</span></div><span class="badge">LIVE</span></div><div class="activity"><div class="activity-item"><i class="dot"></i><div><b>${db.appointments.length} appointments scheduled</b><p>Outpatient calendar is active</p></div></div><div class="activity-item"><i class="dot"></i><div><b>${admitted} patients admitted</b><p>Care teams are assigned</p></div></div><div class="activity-item"><i class="dot"></i><div><b>${db.beds.filter(b=>b.status==='Available').length} beds available</b><p>Across all wards</p></div></div><div class="activity-item"><i class="dot"></i><div><b>Local backup enabled</b><p>Data persists in browser storage</p></div></div></div></div></section>`}
function patients(){let q=($('#globalSearch').value||'').toLowerCase();let rows=db.patients.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q));$('#content').innerHTML=`<div class="page-head"><div><span class="subtle">CARE RECORDS</span><h2>Patients</h2></div><button class="btn gold" onclick="patientModal()">＋ Add patient</button></div><div class="toolbar"><input id="patientSearch" placeholder="Search patient, condition, doctor..." value="${esc(q)}"><select onchange="filterPatients(this.value)"><option value="">All statuses</option><option>Admitted</option><option>Stable</option><option>Discharged</option></select></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Patient</th><th>Age / Sex</th><th>Condition</th><th>Doctor</th><th>Status</th><th></th></tr></thead><tbody>${rows.length?rows.map(p=>`<tr><td>${p.id}</td><td><div class="patient"><span class="mini-avatar">${initials(p.name)}</span><b>${esc(p.name)}</b></div></td><td>${p.age} / ${p.gender[0]}</td><td>${esc(p.condition)}</td><td>${esc(p.doctor)}</td><td><span class="badge ${p.status==='Discharged'?'warn':''}">${p.status}</span></td><td><button class="btn ghost" onclick="deletePatient('${p.id}')">Delete</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty">No patient records found.</td></tr>`}</tbody></table></div></div>`;$('#patientSearch').oninput=()=>{ $('#globalSearch').value=$('#patientSearch').value;patients() }}
function filterPatients(v){let q=($('#patientSearch').value||'').toLowerCase();let old=db.patients;db.patients=old;$('#globalSearch').value=q;let rows=old.filter(p=>(!v||p.status===v)&&Object.values(p).join(' ').toLowerCase().includes(q));$('#patientSearch').value=q;patients();}
function patientModal(){openModal(`<h3>Add patient</h3><div class="form"><div class="form-row"><label>Name<input id="mName" placeholder="Full name"></label><label>Age<input id="mAge" type="number" placeholder="Age"></label></div><div class="form-row"><label>Gender<select id="mGender"><option>Female</option><option>Male</option><option>Other</option></select></label><label>Status<select id="mStatus"><option>Admitted</option><option>Stable</option><option>Discharged</option></select></label></div><div class="form-row"><label>Condition<input id="mCondition" placeholder="e.g. Fever"></label><label>Doctor<select id="mDoctor">${db.doctors.map(d=>`<option>${d.name}</option>`).join('')}</select></label></div></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="addPatient()">Save patient</button></div>`)}
function addPatient(){let name=$('#mName').value.trim();if(!name)return toast('Patient name is required');db.patients.unshift({id:'P-'+Math.floor(1000+Math.random()*8999),name,age:+$('#mAge').value||0,gender:$('#mGender').value,condition:$('#mCondition').value||'General observation',status:$('#mStatus').value,doctor:$('#mDoctor').value});save();closeModal();patients();toast('Patient added successfully')}
function deletePatient(id){db.patients=db.patients.filter(p=>p.id!==id);save();patients();toast('Patient record removed')}
function appointments(){let today='2026-09-08';$('#content').innerHTML=`<div class="page-head"><div><span class="subtle">SCHEDULE</span><h2>Appointments</h2></div><button class="btn gold" onclick="appointmentModal()">＋ New appointment</button></div><div class="cards">${db.appointments.map(a=>`<div class="panel"><div class="panel-head"><span class="badge ${a.status==='Pending'?'warn':''}">${a.status}</span><span class="subtle">${a.date}</span></div><h3 style="font:700 16px 'Space Grotesk';margin:0 0 5px">${esc(a.patient)}</h3><p class="subtle">${esc(a.doctor)} · ${a.type}</p><div style="display:flex;justify-content:space-between;margin-top:18px;align-items:center"><b>${a.time}</b><button class="btn ghost" onclick="toggleAppt('${a.id}')">${a.status==='Pending'?'Confirm':'Mark pending'}</button></div></div>`).join('')}</div>`}
function appointmentModal(){openModal(`<h3>New appointment</h3><div class="form"><label>Patient<select id="aPatient">${db.patients.map(p=>`<option>${p.name}</option>`).join('')}</select></label><div class="form-row"><label>Doctor<select id="aDoctor">${db.doctors.map(d=>`<option>${d.name}</option>`).join('')}</select></label><label>Date<input id="aDate" type="date" value="2026-09-08"></label></div><div class="form-row"><label>Time<input id="aTime" type="time" value="12:00"></label><label>Type<select id="aType"><option>Consultation</option><option>Follow-up</option><option>Review</option></select></label></div></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="addAppointment()">Schedule</button></div>`)}
function addAppointment(){db.appointments.push({id:'A-'+Math.floor(100+Math.random()*899),patient:$('#aPatient').value,doctor:$('#aDoctor').value,date:$('#aDate').value,time:$('#aTime').value,type:$('#aType').value,status:'Pending'});save();closeModal();appointments();toast('Appointment scheduled')}
function toggleAppt(id){let a=db.appointments.find(x=>x.id===id);a.status=a.status==='Pending'?'Confirmed':'Pending';save();appointments()}
function doctors(){$('#content').innerHTML=`<div class="page-head"><div><span class="subtle">CLINICAL TEAM</span><h2>Doctors</h2></div><button class="btn gold" onclick="doctorModal()">＋ Add doctor</button></div><div class="cards">${db.doctors.map(d=>`<div class="panel"><div class="doctor-card"><div class="doctor-photo">${initials(d.name.replace('Dr. ',''))}</div><div><h4>${esc(d.name)}</h4><p>${esc(d.specialty)} · Room ${esc(d.room)}</p><span class="badge ${d.status==='Off duty'?'warn':''}">${d.status}</span></div></div></div>`).join('')}</div>`}
function doctorModal(){openModal(`<h3>Add doctor</h3><div class="form"><label>Full name<input id="dName" placeholder="Dr. Name"></label><div class="form-row"><label>Specialty<input id="dSpec" placeholder="Specialty"></label><label>Room<input id="dRoom" placeholder="A-101"></label></div></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="addDoctor()">Add doctor</button></div>`)}
function addDoctor(){let name=$('#dName').value.trim();if(!name)return toast('Doctor name is required');db.doctors.push({name:name.startsWith('Dr.')?name:'Dr. '+name,specialty:$('#dSpec').value||'General Medicine',room:$('#dRoom').value||'TBD',status:'On duty'});save();closeModal();doctors();toast('Doctor added')}
function wards(){let occ=db.beds.filter(b=>b.status==='Occupied').length;$('#content').innerHTML=`<div class="page-head"><div><span class="subtle">CAPACITY</span><h2>Wards & Beds</h2></div><div><span class="badge">${db.beds.length-occ} available</span></div></div><div class="stats"><div class="stat"><div class="stat-top"><span>Total beds</span></div><h3>${db.beds.length}</h3></div><div class="stat"><div class="stat-top"><span>Occupied</span></div><h3>${occ}</h3></div><div class="stat"><div class="stat-top"><span>Available</span></div><h3>${db.beds.filter(b=>b.status==='Available').length}</h3></div><div class="stat"><div class="stat-top"><span>Clean / ready</span></div><h3>${db.beds.filter(b=>b.status==='Clean').length}</h3></div></div><div class="panel"><div class="panel-head"><div><h3>Bed board</h3><span class="subtle">Tap a bed to cycle its status</span></div></div><div class="bed-grid">${db.beds.map(b=>`<button class="bed ${b.status.toLowerCase()}" onclick="cycleBed(${b.no})">B-${String(b.no).padStart(2,'0')}<br><small>${b.status}</small><br><small>${b.ward}</small></button>`).join('')}</div></div>`}
function cycleBed(n){let b=db.beds.find(x=>x.no===n);b.status=b.status==='Available'?'Occupied':b.status==='Occupied'?'Clean':'Available';save();wards()}
function billing(){$('#content').innerHTML=`<div class="page-head"><div><span class="subtle">FINANCE</span><h2>Billing</h2></div><button class="btn gold" onclick="invoiceModal()">＋ New invoice</button></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Patient</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${db.invoices.map(i=>`<tr><td><b>${i.id}</b></td><td>${esc(i.patient)}</td><td>${i.date}</td><td><b>₹${i.amount.toLocaleString('en-IN')}</b></td><td><span class="badge ${i.status==='Pending'?'warn':''}">${i.status}</span></td><td><button class="btn ghost" onclick="toggleInvoice('${i.id}')">${i.status==='Paid'?'Mark pending':'Mark paid'}</button></td></tr>`).join('')}</tbody></table></div></div>`}
function invoiceModal(){openModal(`<h3>New invoice</h3><div class="form"><label>Patient<select id="iPatient">${db.patients.map(p=>`<option>${p.name}</option>`).join('')}</select></label><label>Amount (₹)<input id="iAmount" type="number" placeholder="5000"></label></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="addInvoice()">Create invoice</button></div>`)}
function addInvoice(){let amount=+$('#iAmount').value;if(!amount)return toast('Enter an amount');db.invoices.unshift({id:'INV-'+Math.floor(100+Math.random()*899),patient:$('#iPatient').value,amount,status:'Pending',date:'2026-09-08'});save();closeModal();billing();toast('Invoice created')}
function toggleInvoice(id){let i=db.invoices.find(x=>x.id===id);i.status=i.status==='Paid'?'Pending':'Paid';save();billing()}
function settings(){$('#content').innerHTML=`<div class="page-head"><div><span class="subtle">PREFERENCES</span><h2>Settings</h2></div></div><div class="panel"><h3 style="font:700 17px 'Space Grotesk'">Browser-only mode</h3><p class="subtle" style="max-width:600px;line-height:1.7">AfroCare is intentionally static. Patient, appointment, ward and billing data is stored in this browser using localStorage. Nothing is sent to a server.</p><div style="display:flex;gap:8px;margin-top:18px"><button class="btn" onclick="exportData()">Export JSON</button><button class="btn ghost" onclick="resetData()">Reset demo data</button></div></div>`}
function exportData(){let a=document.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(db,null,2));a.download='afrocare-backup.json';a.click();toast('Backup exported')}
function resetData(){if(confirm('Reset all local data to the demo dataset?')){db=JSON.parse(JSON.stringify(seed));save();render();toast('Demo data restored')}}
function openModal(html){$('#modal').innerHTML=html;$('#modalBackdrop').classList.add('show')}function closeModal(){$('#modalBackdrop').classList.remove('show')}
function go(p){current=p;let m={dashboard:['Dashboard','Overview'],patients:['Patients','Care records'],appointments:['Appointments','Schedule'],doctors:['Doctors','Clinical team'],wards:['Wards & Beds','Capacity'],billing:['Billing','Finance'],settings:['Settings','Preferences']}[p];layout(m[0],m[1]);document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#sidebar').classList.remove('open')}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#globalSearch').oninput=()=>{if(current!=='patients')go('patients');else patients()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('afrocare_dark',document.body.classList.contains('dark'))};if(localStorage.getItem('afrocare_dark')==='true')document.body.classList.add('dark');render();